# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skipper < Formula
  desc "skipper is a tunnel and a reverse proxy that enables you to share your localhost free using just a subdomain from the skipper.lat domain"
  homepage "https://skipper.lat"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juandi247/Skipper/releases/download/v1.0.0/skipper_1.0.0_darwin_amd64.tar.gz"
      sha256 "2f94c766459e8e4978e3a9f4a9cb6862107bfb3032cc7fda637b3b5be10039f5"

      def install
        bin.install "skipper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juandi247/Skipper/releases/download/v1.0.0/skipper_1.0.0_darwin_arm64.tar.gz"
      sha256 "21416a91881cba93fb495ae206bc26be2f79dce8fba5f334e23fe2a9e086241f"

      def install
        bin.install "skipper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/juandi247/Skipper/releases/download/v1.0.0/skipper_1.0.0_linux_amd64.tar.gz"
      sha256 "384aabd5bb3124b8713781ecf30f5a4591fcb0a5fb981bf700e0fdf157096050"
      def install
        bin.install "skipper"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/juandi247/Skipper/releases/download/v1.0.0/skipper_1.0.0_linux_arm64.tar.gz"
      sha256 "ea5190a550b5317c774061e08ba564e18b2839aaa1aa25c2e178cad4476daa14"
      def install
        bin.install "skipper"
      end
    end
  end
end
