# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skipper < Formula
  desc "skipper is a tunnel and a reverse proxy..."
  homepage "https://skipper.lat"
  version "0.0.81"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juandi247/Skipper/releases/download/v0.0.81/skipper_0.0.81_darwin_amd64.tar.gz"
      sha256 "722cce7641e463c3fe7c3ceeea20b80b4068a39c6ecc0ce419ecb763c67e0f21"

      def install
        bin.install "skipper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juandi247/Skipper/releases/download/v0.0.81/skipper_0.0.81_darwin_arm64.tar.gz"
      sha256 "392229a16f3d22e0e92e4c1cb18ceae8bc173b6c1f259f2243222bc36d5095d4"

      def install
        bin.install "skipper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/juandi247/Skipper/releases/download/v0.0.81/skipper_0.0.81_linux_amd64.tar.gz"
      sha256 "013f86aeff0b836c42cc2748245e278877f3e540deeace902bd2bbdefb3eec08"
      def install
        bin.install "skipper"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/juandi247/Skipper/releases/download/v0.0.81/skipper_0.0.81_linux_arm64.tar.gz"
      sha256 "c6d44016e8c6ac4cf394cc041cdc07da217c722ca9653af4aa86d714b82a42b0"
      def install
        bin.install "skipper"
      end
    end
  end
end
