# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skipper < Formula
  desc "skipper is a tunnel and a reverse proxy..."
  homepage "https://skipper.lat"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juandi247/Skipper/releases/download/v0.0.7/skipper_0.0.7_darwin_amd64.tar.gz"
      sha256 "1821724bbb7ec5dacff9c39fa9889dcf716363bb8db7d68b1cc06cd5ce5a71bc"

      def install
        bin.install "skipper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juandi247/Skipper/releases/download/v0.0.7/skipper_0.0.7_darwin_arm64.tar.gz"
      sha256 "bab4c143a941c269242310d02ccbbb26786ca463a417b89e32fb108d83712e15"

      def install
        bin.install "skipper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/juandi247/Skipper/releases/download/v0.0.7/skipper_0.0.7_linux_amd64.tar.gz"
      sha256 "40a2a3ba209e0b5ae6c5e35ab3fafb962dddc41dc656624f718f90dfe228127f"
      def install
        bin.install "skipper"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/juandi247/Skipper/releases/download/v0.0.7/skipper_0.0.7_linux_arm64.tar.gz"
      sha256 "e4d5992186c4e4cb56dad19975fb7b6eed86e5f224a24716a4f7f72fe714651c"
      def install
        bin.install "skipper"
      end
    end
  end
end
